### ISSUE TITLE
Negative & >1 event weights

### ISSUE THREAD

**Issue by marcomuzio** [ara-software/AraSim#145]
Event weights calculated are sometimes greater than 1 (eg. ~200) or negative, the latter of which causes a segfault and crash inside `Counting::incrementEventsFound`. I've only seen this occur when simulating a lot of low energy events <=10^17 eV. Example output showing the negative weight is below:

Large event weight:
```
************************************
PA trigger ~~~ raySolNum: 0  SNR: 4.34358  Event Number : 53391  PA efficiency : 1.00161

Making useful event
StationID: 6
StationID_AraRoot: 3

Global_Pass : 2253 evt : 53391 added weight : 223.391
223.391 : 9
```

Negative event weight:
```
************************************
PA trigger ~~~ raySolNum: 0  SNR: 2.4274  Event Number : 14766  PA efficiency : 0.888228

Making useful event
StationID: 6
StationID_AraRoot: 3

Global_Pass : 2251 evt : 14766 added weight : -241.795
-241.795 : -2147483648

*** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000014fe6f81260c in waitpid () from /lib64/libc.so.6
#1  0x000014fe6f78ff62 in do_system () from /lib64/libc.so.6
#2  0x000014fe74a4fb54 in TUnixSystem::StackTrace() () from /cvmfs/ara.opensciencegrid.org/trunk/RHEL_7_x86_64/root_build/lib/libCore.so
#3  0x000014fe74a5234a in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/ara.opensciencegrid.org/trunk/RHEL_7_x86_64/root_build/lib/libCore.so
#4  <signal handler called>
#5  0x00000000004c184c in Counting::incrementEventsFound(double, Event*) ()
#6  0x0000000000439cb9 in main ()
===========================================================
```

**Comment by Machtay** [comment]
Just saw this and remembered I encountered it before--pretty sure I had a fix that I detailed here: https://aradocs.wipac.wisc.edu/0024/002441/003/AraSim_Effective_Volume_Bug_Presentation.pdf

I dug up a version that does at least part of what I prescribed in those slides (added a line at the bottom of atmosphere.dat) and I'm pretty sure it does work for eliminating at least the high weights. Can look into it more some day.

**Comment by marcomuzio** [comment]
Oh wow really? Do you think you could open a pull request addressing this?

**Comment by Machtay** [comment]
Yeah I can give it a try, do you have a specific event (like a number seed or something) that gives a high/negative weight? Otherwise I can search for one with many events.

**Comment by marcomuzio** [comment]
No sorry, I didn't keep track of the setup file I needed to produce this. I just noticed it _seemed_ to come up when simulating a lot of low energy events < 10^17 eV.

**Comment by marcomuzio** [comment]
Seems like people have managed to generate them when running noise simulations at a rate of roughly 1 for every 10k events. So maybe that's the place to start.
